Mfoggia/add column alignment custom rule
silvermine/standardization pull request #65
Opened 2023-06-29 20:43 UTC by MrMarCode

2023-06-29 21:00 UTC, onebytegone requested changes

2023-06-29 21:00 UTC, onebytegone commented on .markdownlint-cli2.shared.cjs
> +const indentAlignment = require('./node_modules/@silvermine/markdownlint-rule-indent-alignment/src/indent-alignment.js')
Does this work?

```suggestion
const indentAlignment = require('@silvermine/markdownlint-rule-indent-alignment')
```

2023-06-30 13:27 UTC, MrMarCode commented on .markdownlint.json
> +
Yes, from my testing it seems that unused rule configs are ok.

2023-06-30 13:57 UTC, onebytegone requested changes

2023-06-30 13:57 UTC, onebytegone commented on .markdownlint-cli2.shared.cjs
> +const indentAlignment = require('@silvermine/markdownlint-rule-indent-alignment')
```suggestion
const indentAlignment = require('@silvermine/markdownlint-rule-indent-alignment');
```

2023-06-30 13:57 UTC, onebytegone commented on .markdownlint.json
> +
The requested change for the extra whitespace?

2023-06-30 14:51 UTC, onebytegone approved these changes

2023-06-30 15:34 UTC, merged